config/routes.rb
Chunqiu::Application.routes.draw do
  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'login'  => 'sessions#new',     :as => 'login'
  get 'signup' => 'users#new',        :as => 'signup'
  root :to => 'users#new'
  resources :users do
    resources :cities
  end  
  resources :sessions

  scope :path => '/:city_id', :as => 'city' do
    resources :solider_queues
    resources :fights
  end
  

end

app/models/solider_queue.rb
# -*- coding: utf-8 -*-
class SoliderQueue < ActiveRecord::Base

  belongs_to :city

  Codes = {'等待' => 0, '完成' => 1, '放弃' => -1}

  def solider_kind_name
    Solider::CodeToName[solider_kind]    
  end

  # 取消训练队列
  def remove_delayed
    Resque.remove_delayed(get_queue_class, :sq_id => self.id)
  end

  def get_queue_class
    case solider_kind
    when Solider::Codes['长枪兵']; MediumCity::CreateCQB
    when Solider::Codes['弓箭手']; MediumCity::CreateGJS
    when Solider::Codes['骑兵']; MediumCity::CreateQB
    end  
  end

  # 撤销训练后，退金子
  def gold_needed_return
    gold = case solider_kind
    when Solider::Codes['长枪兵']; 1
    when Solider::Codes['弓箭手']; 3
    when Solider::Codes['骑兵']; 10
    end  
    total_gold = gold * solider_num
  end

  def return_gold
    gold_num = gold_needed_return
    city.increment(:gold, gold_num )
    city.save
  end
  
end

app/controllers/solider_queues_controller.rb
# -*- coding: utf-8 -*-
class SoliderQueuesController < ApplicationController

  before_filter :authenticate_user
  before_filter :find_city

  def new
  end

  # 增加一批新的训练士兵的任务
  def create
    if @city.waiting_solider_queues.count >= 5
      flash[:notice] = '等待接受训练的批次已经达到5批'
      redirect_to :action => 'new'
      return
    end
    solider = params[:solider]
    case solider[:kind].to_i
    when Solider::Codes['长枪兵']
      Solider.study_cqb(@city.id, solider[:num].to_i)
    when Solider::Codes['弓箭手']
      Solider.study_gjs(@city.id, solider[:num].to_i)
    when Solider::Codes['骑兵']
      Solider.study_qb(@city.id, solider[:num].to_i)
    end
    redirect_to :action => 'new'
  end

  # 取消士兵训练队伍，并且退换金子
  def destroy
    sq = SoliderQueue.find(params[:id])
    sq.remove_delayed
    sq.return_gold
    sq.destroy
    redirect_to :action => 'new'
  end

  private
  
  def find_city
    @city = current_user.cities.find(params[:city_id])
  end

end

app/helpers/solider_queues_helper.rb
module SoliderQueuesHelper
end

app/views/solider_queues/new.html.erb
<div class='flash'>
  <p><%= flash[:notice] %></p>
</div>  
<div class="ino">
  <h2><%= @city.name %>:训练士兵</h2>
  <p>金子:<span><%= @city.gold %></span></p>
  <p>食物:<span><%= @city.h_food %></span></p>
  <p>长枪兵:<span><%= @city.cqb_soliders.count %></span></p>
  <p>弓箭手:<span><%= @city.gjs_soliders.count %></span></p>
  <p>骑兵:<span><%= @city.qb_soliders.count %></span></p>
</div>

<div class="sq">
<% if @city.waiting_solider_queues.count > 0 %>
  <h2>正在训练的士兵队列</h2>
  <ul>
  <% @city.waiting_solider_queues.each do |solider_queue| %>
     <li>士兵数量:<span><%= solider_queue.solider_num %></span>, 种类:<span><%= solider_queue.solider_kind_name %></span>
       <%= form_tag city_solider_queue_url(@city.id, solider_queue.id), :method => 'delete' do%>
       <%= submit_tag '撤销训练', :name => nil %>
       <% end %>
     </li>
  <% end %>
  </ul>
</div>  
  
<% end %>

<%= form_tag city_solider_queues_url do -%>
  <label>选择兵种:</label>
  <%= select_tag 'solider[kind]', options_from_collection_for_select(Solider::Kinds, 'code', 'name')%>
  <label>士兵数量</label>
  <input type='text' name='solider[num]' />
  <div>
    <input type='submit' value='提交'/>
    <%= link_to '放弃', user_cities_url(current_user) %>
  </div>
<% end %>